name: spin-solver
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.0.1
  - torchvision=0.2.2
  - numpy=1.13.3
  - pandas=0.24.2
  - matplotlib=2.0.2
  - scipy=1.2.1
  - jupyter
  - pip
  - pip:
      - objgraph==3.4.1
      - python-graphviz==0.10.1
